### PR TITLE
fix: show continuous stats during batch updates

### LINKED ISSUE #939: [FEATURE] Show processed document stats continuously
When users run `cocoindex update`, we want to show stats about processed documents 

Currently we only print it at a pass of processing is done. Related code:
- [Rust code to generate the stats string](https://github.com/cocoindex-io/cocoindex/blob/d03a639594b3001fd3cb55f250506bd4c63caa10/src/execution/stats.rs#L99-L147)
- [Existing code to print the stats](https://github.com/cocoindex-io/cocoindex/blob/d03a639594b3001fd3cb55f250506bd4c63caa10/src/execution/live_updater.rs#L111-L124)

We want to continuously print updated stats (e.g. every second) so users know it keeps going.

---
❤️ Contributors, please refer to 📙[Contributing Guide](https://cocoindex.io/docs/about/contributing).
Unless the PR can be sent immediately (e.g. just a few lines of code), we recommend you to leave a comment on the issue like **`I'm working on it`**  or **`Can I work on this issue?`** to avoid duplicating work. Our [Discord server](https://discord.com/invite/zpA9S2DR7s) is always open and friendly.

### PR DESCRIPTION
**Pull request by thisisharsh7**
## Summary
  Fixes #939 
  
  ## Problem
  Previously, when running `cocoindex update`, stats about processed documents were only printed once a full processing pass completed. For long-running updates, users had no visibility into ongoing progress, making it unclear if the process was  still working.
  
  ## Solution
   Implemented continuous stats reporting by spawning a background task.
   
   ## Example Output
Screenshot 2025-10-20 at 11 14 13 AM

### CODE REVIEW

**Comment by thisisharsh7** [comment]
kindly review it and let me know for any changes thanks!

File: src/execution/live_updater.rs [hunk 1]
```diff
@@ -329,7 +329,40 @@ impl SourceUpdateTask {
...
+                    let current_stats = update_stats_clone.as_ref().clone();
+                    let delta = current_stats.delta(&last_stats);
+                    if delta.has_any_change() {
+                        // Print periodic progress (do NOT merge here, final report_stats will merge)
+                        println!(
+                            "{}.{} ({update_title_owned}): {}",
+                            flow_name, import_op_name, delta
+                        );
+                        last_stats = current_stats;
+                    }
```
Comment (georgeh0) [inline src/execution/live_updater.rs]: Is it possible to always show the latest stats (instead of the delta), and keep overwriting the stats line showing before? For users, they always see the last line showing the current stats.

Did a brief research, and [indicatif](https://github.com/console-rs/indicatif) crate seems good for this purpose.

**Review by georgeh0 — COMMENTED** [review]
Thanks a lot for the PR!

File: src/execution/live_updater.rs (hunk 1 above)
Comment (thisisharsh7) [reply src/execution/live_updater.rs]: got it wil check and apply the changes

Comment (thisisharsh7) [reply src/execution/live_updater.rs]: https://github.com/user-attachments/assets/ac8bebd3-0351-4c8c-bac8-9e4cccfe9685

is this right?

Comment (georgeh0) [reply src/execution/live_updater.rs]: That's awesome! Thanks!

Please push your commits.

**Comment by thisisharsh7** [comment]
please check and lmk for any updates
